---
title: "rstudiovim"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rstudiovim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Welcome. This is an intro to usage of the {rstudiovim} package, and assumes you
have knowledge of Vim motions. We will go over keybinding ex commands:

## Keybinding commands

RStudio offers a few commands for dealing with key bindings:
^[You can see more available commands by looking through the RStudio 
[default Ex Command map](https://github.com/rstudio/rstudio/blob/4f7063b13bb0bae8377639a36d3ff4b7626de6e3/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/keybinding-vim-uncompressed.js#L991C7-L991C26) on GitHub.]

- `imap` - insert mode.
- `nmap` - normal mode.
- `vmap` - visual mode.
- `map`  - for both normal and visual modes. 

The general structure then goes like this:

`<map_command> <new_key_sequence> <keys_to_execute>`

For example to bind home-row keys to exit from insert mode to normal mode, the 
command could be:

`imap jk <Esc>` 

Note the _i_ map, so this binding applies when you are insert mode. 
So, when you are in insert mode, the key sequence `jk` is mapped to the 
`Esc` key, which is the typical way to move from insert mode to normal mode.

### Executing commands

Assuming you already have Vim keybindings active in the RStudio source editor,
you can bring up Vim command mode from normal mode by pressing `:`, then type
your command and press `Enter` to execute it.

So starting in normal mode press the keys, you could apply the example
keybinding with `imap jk <Esc>`, in full pressing the keys `:` `i` `m` `a` `p`
`<Space>` `j` `k` `<Space>` `<` `E` `s` `c` `>` `<Enter>`.


### Recursive keybindings

One thing to watch out for is that the commands listed above are recursive. If
you use command `map p p`, you won't be able to paste anymore because `p` just
refers to itself instead of the paste command. Pressing `p` will just do
nothing.

At present RStudio does not offer non-recurseive (`nore`) versions of the map
commands typically among Vim ex commands like `noremap`. This means we're mostly
limited to creating commands for _new_ key chains, like `jk` above.

## Applying commands to every session with {rstudiovim}

If we're happy with a command and can run ourselves in RStudio, it should be
relatively straightforward to get that command to run every session. With
{rstudiovim} installed and loaded we can set up a config file and have it
executed every session. If you've read the README, you've already seen
everything you need.

The typical config file is called `.vimrc`. You can create your own version at 
any location and supply the path, but the simplest usage will be with the default
path provided.

```r
file.edit(rsvim_default_path())
```

Then simply add your commands to the file, each on a separate line.You can add
comment lines by preceding them with double quotes `"` like so:

```vim
" home-row exit from insert mode
imap jk <Esc>

```

You must of course save the file! The we just need to point the 

### Rprofile

Your 
[`.Rprofile`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Startup)
is a file containing R code to be executed at the start of every R session.

Be mindful you can have a .Rprofile at both the user level and project level - 
one at project level will be executed instead of user level one, so make sure 
the rsvim call is where you need it.

```r
# User level
file.edit("~/.Rprofile")
# Project level
file.edit(".Rprofile")
```

### Troubleshooting

- First, the Vim implementation is quite limited, so always make sure the command
is one you can execute in RStudio yourself first. If it doesn't there's not much
{rstudiovim} can do about it.

- If something doesn't work that usually does, try restarting the R session and
executing your `rsvim_exec_file()` call again. Sometimes the execution gets 
interrupted by other processes.

- If a command works for you when you type it yourself, but doesn't seem to work with
{rstudiovim}, then there may be an issue in the parsing of your commands and 
translation to keypresses. There is an argument `wait` with which you can specify
seconds to wait between your commands being typed and then executed. In this way
you can review what is actually being typed. If you find a disparity between what
is being typed and what's in your .virmc, please raise (or add to a related) 
[GitHub issue](https://github.com/davidfoord1/rstudiovim/issues). You can use
`rsvim_exec()` for a single command if that helps you narrow the behaviour down.
